locale: "en-US"

title: "Dr. Behzad Hassannezhad Kashani"

name: "Dr. Behzad Hassannezhad Kashani"

description: "Academic website of Dr. Behzad Hassannezhad Kashani"

url: "https://hasannejad.ir"

baseurl: ""

repository: "bhkashani-cmd/academic-site"


remote_theme: "mmistakes/minimal-mistakes"


minimal_mistakes_skin: "default"


author:
  name: "Dr. Behzad Hassannezhad Kashani"
  avatar: "/assets/images/profile.jpg"
  bio: "Researcher, Academic Editor, and Managing Editor of the International Journal of Management, Accounting and Economics (IJMAE)."
  location: "Iran"


include:
  - _pages
  - _publications


collections:
  publications:
    output: true
    permalink: /publication/:path/


defaults:

  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
    values:
      author_profile: true
